Add cookies to Wallaby.HTTPClient
pay-it-off/wallaby pull request #1
Opened 2020-12-02 02:53 UTC by hazen

https://app.clubhouse.io/payitoff/story/3266/make-selenium-load-balancer-sticky

2020-12-02 03:01 UTC, hazen commented on test/support/http_client_case.ex
> +  defp maybe_add_cookies(conn, cookies) do
Extend the testing framework to inject cookies

2020-12-02 03:03 UTC, hazen commented on lib/wallaby/webdriver_client.ex
> +  @spec create_session(String.t(), map) :: {:ok, map, cookies()}
🍗 Return the cookies from the initial request

2020-12-02 22:56 UTC, JEG2 requested changes
Wow.  That's some serious surgery!

![sawing a knee on a kitchen counter](https://media.giphy.com/media/kHfSJw6OLxX9w44gzo/giphy.gif)

One bug in two places, then we're good to go!

2020-12-02 22:56 UTC, JEG2 commented on lib/wallaby/httpclient.ex
> +  def request(method, url, params, [{:encode_json, false} | opts]) do
🐛 I actually spotted this when making my own changes to this file, but this code isn't safe.  

Before the pattern match was `[{:encode_json, false} | _]`.  Because that's a keyword list, not a map, it **doesn't** match _contains_.  It matches _starts with_.  It "worked" before your change because it was the only supported option.  Now that there are two, it would only work if they're passed in the proper order.

I guess the fix is to do something like:

```elixir
  def request(method, url, params, opts) do
    if Keyword.get(opts, :encode_json) == false do
      make_request(method, url, params, opts)
    else
      make_request(method, url, Jason.encode!(params), opts)
    end
  end

  # and remove the branch below
```

It's not sexy.  Open to better ideas.

2020-12-02 22:56 UTC, JEG2 commented on lib/wallaby/httpclient.ex
> +  defp inject_cookies([{:cookies, cookies} | _]) do
See problem above.

2020-12-03 14:33 UTC, JEG2 approved these changes

2020-12-03 15:02 UTC, merged